// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// st_petersburg_game
NumericVector st_petersburg_game(unsigned int n_games, double fee);
RcppExport SEXP _RcppSpg_st_petersburg_game(SEXP n_gamesSEXP, SEXP feeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n_games(n_gamesSEXP);
    Rcpp::traits::input_parameter< double >::type fee(feeSEXP);
    rcpp_result_gen = Rcpp::wrap(st_petersburg_game(n_games, fee));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppSpg_st_petersburg_game", (DL_FUNC) &_RcppSpg_st_petersburg_game, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppSpg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
