# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
st_petersburg_game <- function(n_games = 10L, fee = 10) {
    .Call(`_RcppSpg_st_petersburg_game`, n_games, fee)
}

